---
# Origin: https://github.com/MakarenaLabs/ansible-role-wordpress/blob/master/tasks/main.yml
- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
