---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Verify Apache is serving content.
      uri:
        url: http://localhost/
        status_code: 200
      register: apache_status
      tags: verify

    - name: Verify Apache status.
      debug:
        var: apache_status.status
      tags: verify
